import type { Metadata } from "next";
import Link from "next/link";

const title = "ITパスポート2027年度新試験はどう変わる？今から勉強する人向けガイド";
const description = "ITパスポートは2027年度春頃から新試験制度へ移行予定。IPAが公開したシラバス案Ver.0.1とサンプル問題をもとに、2026年9月時点で分かっていることと今からの勉強方針を整理します。";
const canonical = "/guide/it-passport-2027-new-exam-guide";
export const metadata: Metadata = { title, description, keywords:["ITパスポート 2027","ITパスポート 新試験","ITパスポート 2027 変更","ITパスポート シラバス 2027","ITパスポート サンプル問題","ITパスポート 勉強法"], alternates:{canonical}, openGraph:{title,description,type:"article",url:canonical}, twitter:{card:"summary_large_image",title,description} };
const cta=(p:string)=>`/onboarding?source=2027-new-exam-guide&placement=${p}`;
const faq=[
["2027年度のITパスポート新試験はいつ始まりますか？","IPAは2027年度春頃から新試験制度を開始する予定としています。"],
["2027年度のシラバスは確定していますか？","いいえ。2026年8月31日に公開されたシラバス案Ver.0.1は検討状況に基づく案で、変更される可能性があります。"],
["今から勉強を始めても無駄になりませんか？","基礎的なIT・ビジネス知識の学習自体を止める必要はありません。ただし受験時期によって対象制度が変わるため、まず受験時期を決めて対応教材を選ぶことが重要です。"],
];
const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};
export default function Page(){return <main className="min-h-screen bg-slate-50 text-slate-900"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><span className="font-black text-blue-700">it-learning-app</span><Link href={cta("header")} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white">無料で学習計画を作る</Link></div></header>
<section className="bg-white"><div className="mx-auto max-w-5xl px-5 py-16 md:py-24"><p className="font-bold text-blue-700">2026年9月9日更新｜IPA最新公表情報を整理</p><h1 className="mt-4 text-4xl font-black leading-tight md:text-6xl">ITパスポート<br/>2027年度新試験、<br/>何が分かっている？</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">2026年8月31日、IPAは2027年度のITパスポート向けシラバス案Ver.0.1とサンプル問題を公開しました。ただし、まだ「案」です。これから受験する人が必要なのは、不確定な変更点を暗記することではなく、自分が2026年中と2027年度のどちらを受けるのか決めることです。</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={cta("hero")} className="rounded-xl bg-blue-600 px-7 py-4 text-center font-bold text-white">無料で受験時期から学習計画を作る →</Link><a href="https://www3.jitec.ipa.go.jp/JitesCbt/html/about/range.html" target="_blank" rel="noreferrer" className="rounded-xl border px-7 py-4 text-center font-bold">IPA公式情報を見る</a></div></div></section>
<section className="mx-auto max-w-5xl px-5 py-16"><h2 className="text-3xl font-black">2026年9月時点で確定していること</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[["01","開始時期","2027年度春頃から新試験制度へ移行予定。"],["02","公式資料","シラバス案Ver.0.1とサンプル問題が公開済み。"],["03","まだ変わり得る","シラバス案は今後変更される可能性あり。"]].map(([n,h,p])=><div key={n} className="rounded-2xl border bg-white p-6"><span className="font-black text-blue-600">{n}</span><h3 className="mt-3 text-xl font-black">{h}</h3><p className="mt-3 leading-7 text-slate-600">{p}</p></div>)}</div></section>
<section className="border-y bg-white"><div className="mx-auto max-w-5xl px-5 py-16"><h2 className="text-3xl font-black">今から勉強するなら、まず受験時期を決める</h2><div className="mt-7 overflow-x-auto"><table className="w-full min-w-[680px] border-collapse"><thead><tr className="bg-slate-100"><th className="p-4 text-left">状況</th><th className="p-4 text-left">考え方</th><th className="p-4 text-left">次の行動</th></tr></thead><tbody>{[["すでに現行教材で学習中","2026年内受験を検討","現在地を測り年内合格までの距離を確認"],["年内に資格が必要","2026年受験を優先","会場・日程を確認して逆算"],["取得期限がない","2027年度も選択肢","正式情報の更新を追いながら基礎学習"],["まだ迷っている","制度より現在地を先に確認","初見問題で得意・弱点を測る"]].map(r=><tr key={r[0]} className="border-t">{r.map((c,i)=><td key={c} className={`p-4 ${i===0?"font-bold":""}`}>{c}</td>)}</tr>)}</tbody></table></div></div></section>
<section className="mx-auto max-w-5xl px-5 py-16"><h2 className="text-3xl font-black">新試験だから、勉強を待つ必要はない</h2><p className="mt-4 max-w-3xl leading-8 text-slate-600">制度変更前は「教材が出揃うまで何もしない」という判断をしがちです。しかし、ITパスポートで問われる基礎知識を学ぶことと、最終的な試験対策は分けて考えられます。まず問題を解いて現在地を測り、理解できていない基礎を埋める。そのうえで受験する制度に合わせて仕上げる方が、学習を止めずに済みます。</p><div className="mt-8 rounded-3xl bg-blue-50 p-7"><h3 className="text-2xl font-black">AIを使うなら「変更点予想」より「理解支援」</h3><p className="mt-3 leading-7 text-slate-600">生成AIは、用語の言い換え、似た概念の比較、誤答理由の分析に使えます。一方、未確定の新試験内容を予想させて暗記するのは避け、試験制度の情報はIPA公式を基準にしてください。</p></div></section>
<section className="bg-slate-900 text-white"><div className="mx-auto max-w-5xl px-5 py-16"><p className="font-bold text-blue-300">it-learning-app</p><h2 className="mt-2 text-3xl font-black">制度が変わっても、最初にやることは同じ。</h2><p className="mt-4 max-w-3xl leading-8 text-slate-300">問題を解いて現在地を測り、弱点を見つけ、必要な学習へ絞る。it-learning-appは学習結果から「次に何をするか」を決めることで、受験日までの学習を迷いにくくします。</p><Link href={cta("mid")} className="mt-6 inline-block rounded-xl bg-white px-7 py-4 font-bold text-blue-700">無料で現在地から学習計画を作る →</Link></div></section>
<section className="mx-auto max-w-4xl px-5 py-16"><h2 className="text-3xl font-black">よくある質問</h2><div className="mt-7 space-y-4">{faq.map(([q,a])=><details key={q} className="rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 leading-7 text-slate-600">{a}</p></details>)}</div><div className="mt-12 rounded-3xl bg-blue-50 p-8 text-center"><h2 className="text-3xl font-black">2026年か2027年度か。まず今の実力を知る。</h2><p className="mt-3 text-slate-600">現在地から、受験時期と必要な学習を整理します。</p><Link href={cta("bottom")} className="mt-6 inline-block rounded-xl bg-blue-600 px-7 py-4 font-bold text-white">無料で自分専用の学習計画を作る →</Link></div></section></main>}
