import type { Metadata } from "next";
import Link from "next/link";
const title="ITパスポート試験1週間前に何をする？7日間の直前対策【2026年】";
const description="ITパスポート試験1週間前の勉強法を7日間のスケジュールで解説。新しい教材を増やさず、弱点の再測定と復習に集中する直前対策です。";
const path="/guide/it-passport-7-days-study-plan-2026";
export const metadata:Metadata={title,description,keywords:["ITパスポート 1週間前","ITパスポート 直前","ITパスポート 1週間 勉強","ITパスポート 試験前","ITパスポート 直前対策"],alternates:{canonical:path},openGraph:{title,description,type:"article",url:path}};
const cta=(p:string)=>`/onboarding?source=7-days-study-plan-2026&placement=${p}`;
const days=[["7日前","初見問題で現在地を測る"],["6日前","最大の弱点だけ復習"],["5日前","2番目の弱点を復習"],["4日前","別問題で再測定"],["3日前","分野横断で演習"],["2日前","残った穴だけ復習"],["前日","軽く確認して早く終える"]];
export default function Page(){return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><b className="text-blue-700">it-learning-app</b><Link href={cta("header")} className="rounded-lg bg-blue-600 px-4 py-2 text-white">無料で弱点を確認</Link></div></header><section className="bg-white"><div className="mx-auto max-w-5xl px-5 py-20"><p className="font-bold text-red-600">試験まであと7日</p><h1 className="mt-4 text-4xl font-black md:text-6xl">ITパスポート試験1週間前。<br/>もう「全部」はやらない。</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">残り1週間で重要なのは学習量を増やすことではなく、失点する場所を減らすこと。問題で現在地を測り、弱点だけ復習し、別問題で改善を確かめます。</p><Link href={cta("hero")} className="mt-8 inline-block rounded-xl bg-blue-600 px-7 py-4 font-bold text-white">無料で今の弱点を確認する →</Link></div></section><section className="mx-auto max-w-4xl px-5 py-16"><h2 className="text-3xl font-black">直前1週間でやらないこと</h2><p className="mt-4 leading-8 text-slate-600">参考書を最初から読み直す、新しい教材を追加する、同じ問題の答えだけを覚える。この3つを避け、間違えた論点に時間を集中させます。</p><h2 className="mt-14 text-3xl font-black">7日間の直前スケジュール</h2><div className="mt-7 space-y-3">{days.map(([d,x])=><div key={d} className="grid grid-cols-[90px_1fr] rounded-xl border bg-white p-5"><b className="text-blue-700">{d}</b><span>{x}</span></div>)}</div></section><section className="bg-slate-900 text-white"><div className="mx-auto max-w-4xl px-5 py-16"><h2 className="text-3xl font-black">AIは直前期の「分からない」を短くする</h2><p className="mt-4 leading-8 text-slate-300">生成AIは用語の言い換え、似た概念の比較、誤答理由の整理に使えます。一方、優先順位は実際の問題結果から決めます。AIで理解を助け、学習履歴で次にやることを決める使い分けが有効です。</p></div></section><section className="mx-auto max-w-4xl px-5 py-16"><div className="rounded-3xl bg-blue-50 p-8 text-center"><h2 className="text-3xl font-black">残り7日。まず、今の弱点を知る。</h2><p className="mt-3 text-slate-600">全部をやり直す前に、合格まで不足しているところから始めます。</p><Link href={cta("bottom")} className="mt-6 inline-block rounded-xl bg-blue-600 px-7 py-4 font-bold text-white">無料で自分専用の直前プランを作る →</Link></div></section></main>}
